<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>MisteryApp.Web.Core</RootNamespace>
    <AssemblyName>MisteryApp.Web.Core</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FluentValidation.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MisteryApp.Abstractions\MisteryApp.Abstractions.csproj" />
    <ProjectReference Include="..\MisteryApp.Implementation\MisteryApp.Implementation.csproj" />
    <ProjectReference Include="..\MisteryApp.Common\MisteryApp.Common.csproj" />
  </ItemGroup>
</Project>
