<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>MisteryApp.Web.Server</RootNamespace>
    <AssemblyName>MisteryApp.Web.Server</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <SpaRoot>../misteryapp.web.client/</SpaRoot>
  </PropertyGroup>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\MisteryApp.Web.Core\MisteryApp.Web.Core.csproj" />
    <ProjectReference Include="..\MisteryApp.Implementation\MisteryApp.Implementation.csproj" />
    <ProjectReference Include="..\MisteryApp.Repository\MisteryApp.Repository.csproj" />
  </ItemGroup>
</Project>
